Vagrant.configure("2") do |config|
 config.vm.box = "opscode-ubuntu-14.0"
 config.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.10_chef-provisionerless.box"
 config.omnibus.chef_version = :latest
 config.vm.provision :chef_client do |chef|
  chef.provisioning_path = "/etc/chef"
    chef.chef_server_url = "https://api.chef.io/organizations/crazymf"
    chef.validation_key_path = "/Users/d.khairullin/chef-repo/.chef/crazymf-validator.pem"
    chef.validation_client_name = "crazymf-validator"
    chef.node_name = "hello_world"
 end
end
